# Generated by Django 5.0.6 on 2024-06-21 09:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reiting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reiting',
            options={'verbose_name': 'Отзывы'},
        ),
        migrations.CreateModel(
            name='Uslugs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='логотип')),
                ('users', models.ManyToManyField(null=True, related_name='uslugs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курсы',
            },
        ),
    ]
