# Generated by Django 5.0.6 on 2024-06-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_workers_alter_uslugs_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zaiavki',
            options={'verbose_name': 'Заявки на сертификаты', 'verbose_name_plural': 'Заявка на сертификат'},
        ),
        migrations.AddField(
            model_name='workers',
            name='role',
            field=models.CharField(default=111, max_length=255, verbose_name='Должность'),
            preserve_default=False,
        ),
    ]
