# Generated by Django 5.0.6 on 2024-06-24 05:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_zaiavki_options_workers_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participationapplication',
            options={'verbose_name': 'Заявка на участие', 'verbose_name_plural': 'Заявки на участие'},
        ),
        migrations.AlterModelOptions(
            name='reiting',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='zaiavki',
            options={'verbose_name': 'Заявка на сертификаты', 'verbose_name_plural': 'Заявки на сертификат'},
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона')),
                ('kater', models.ImageField(blank=True, null=True, upload_to='', verbose_name='катер')),
                ('kolichestvo', models.IntegerField(verbose_name='Количество участников')),
                ('komment', models.CharField(max_length=255, verbose_name='Комментарий')),
                ('users', models.ManyToManyField(null=True, related_name='zakaz', to=settings.AUTH_USER_MODEL)),
                ('usluga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zakazuslugi', to='main.uslugs', verbose_name='Вид услуги')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
