# Generated by Django 5.0.6 on 2024-06-24 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_participationapplication_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='updated',
        ),
    ]
