# Generated by Django 5.0.6 on 2024-06-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_zakaz_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zakaz',
            name='created',
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
