# Generated by Django 5.0.6 on 2024-06-25 06:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_zakaz_created_alter_zakaz_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('kater', models.ImageField(blank=True, null=True, upload_to='', verbose_name='катер')),
                ('opisanie', models.CharField(max_length=255, verbose_name='Описание катера')),
            ],
            options={
                'verbose_name': 'Катер',
                'verbose_name_plural': 'Катеры',
            },
        ),
        migrations.RemoveField(
            model_name='participationapplication',
            name='course',
        ),
        migrations.AlterField(
            model_name='participationapplication',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+999999999'. До 15 цифр в длину.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='zakaz',
            name='kater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kater', verbose_name='катер'),
        ),
        migrations.CreateModel(
            name='Remont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Дата ремонта')),
                ('usluga', models.CharField(max_length=255, verbose_name='Описание ремонта')),
                ('kater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vidkatera', to='main.kater', verbose_name='Катер')),
                ('mehanik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mehanik', to=settings.AUTH_USER_MODEL, verbose_name='Механик')),
            ],
            options={
                'verbose_name': 'Ремонт',
                'verbose_name_plural': 'Ремонты',
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
